const swaggerAutogen = require("swagger-autogen")();
const dotenv = require("dotenv");

dotenv.config();

const doc = {
  info: {
    version: "1.0.0",
    title: " api",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: process.env.SWAGGER_URL,
  basePath: "/",
  schemes: ["http", "https"],
  consumes: ["application/json"],
  produces: ["application/json"],

  tags: [
    {
      name: "User",
      description: "Endpoints",
    },
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header", // can be "header", "query" or "cookie"
      name: "authorization", // name of the header, query parameter or cookie
      description: "any description...",
    },
  },
  definitions: {
    loginAdmin: {
      email_id: "admin@gmail.com",
      password: "admin@123456789",
    },
    loginCustomer: {
      email_id: "admin@gmail.com",
      password: "admin@123456789",
    },
    adminAddCustomerController: {
      full_name: "tj",
      email_id: "axyz@gmail.com",
      profile_picture: "base64",
      password: "12345678",
      phone_number: 989278782,
      actionByUserId: 1000,
    },
    addCustomerController: {
      full_name: "tj",
      email_id: "axyz@gmail.com",
      profile_picture: "base64",
      password: "12345678",
      phone_number: 989278782,
      actionByUserId: 0,
    },
    updateCustomerController: {
      full_name: "tj",
      profile_picture: "base64",
      actionByUserId: 1,
      phone_number: 12423435,
      id: 1,
    },
    activateDeactivateCustomerAccountController: {
      account_status: false,
      id: 1,
    },
  },
};

const outputFile = "./swagger_output.json";
const endpointsFiles = [
  "./src/routes/admin.routes.ts",
  "./src/routes/customer.routes.ts",
];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("./server.ts"); // Your project's root file
});
